### ISSUE TITLE
Auth flow

### ISSUE THREAD

**Issue by markobogoevski** [nordigen/nordigen-python#16]
Hello, I have a question regarding the auth flow. I have two accounts integrated with a bank. Do I always have to go through the step of generating a link and authenticating through the browser window in order for the accounts to be filled out? Does the requisition id remain static or?

**Comment by safriks** [comment]
Hi Marko,

No, you do it once and then can access data for up to 90 days (default) or as many an you have specified in POST
[​/api​/v2​/agreements​/enduser​/](https://nordigen.com/en/docs/account-information/integration/parameters-and-responses/#/agreements/create%20EUA%20v2) under parameter "access_valid_for_days"

The requisition id remains static for the duration of authorized acces, but you gotta generate a new one after the access expires after 90 days. The process is described here:
https://nordigen.zendesk.com/hc/en-gb/articles/6760603000349-How-to-regain-access-to-an-account-once-the-access-has-expired-

Hope this helps ^^
