### ISSUE TITLE
Type hints are incorrect according to the API schema

### ISSUE THREAD

**Issue by saschametz** [nordigen/nordigen-python#17]
Hello, I've noticed that several type hints are incorrect. For reference, I checked the official [API schema](https://nordigen.com/en/docs/account-information/integration/parameters-and-responses/).
Below are some examples:

---

https://github.com/nordigen/nordigen-python/blob/c8b91669a63b4cd12df8e0ba72d47f8df822286e/nordigen/types/types.py#L22-L30
- `enduser_id` is not available in the API response
[Ref to API Schema](https://nordigen.com/en/docs/account-information/integration/parameters-and-responses/#/agreements/retrieve%20EUA%20by%20id%20v2)

---

https://github.com/nordigen/nordigen-python/blob/c8b91669a63b4cd12df8e0ba72d47f8df822286e/nordigen/types/types.py#L40-L50
- `agreements` isn't available in the API response, but instead `agreement` (string instead of list) is available
- `enduser_id` is not available in the API response
- `link` property is missing in type hints
- `ssn` property is missing in type hints
- `account_selection` property is missing in type hints
- `redirect_immediate` property is missing in type hints
- `results` isn't part of that object
[Ref to API Schema
](https://nordigen.com/en/docs/account-information/integration/parameters-and-responses/#/requisitions/requisition%20by%20id)

**Comment by saschametz** [comment]
@victory-sokolov Hi Viktor, do you to know if there's a plan to make sure the types match up with the API schema?

**Comment by hmol** [comment]
Maybe pydantic could be of use here?
