### ISSUE TITLE
exchange_token doesn't return correct information

### ISSUE THREAD

**Issue by Robin-Dillen** [nordigen/nordigen-python#18]
**Describe the bug**
When calling the exchange token function, it only returns the new access token and access expiration date, and not the refresh token as said in the docstring.

**To Reproduce**
1. Create Nordigen client
2. call client.exchange_token

**Expected behavior**
I expected to receive a new TokenType with a new access and refresh token in it

**Comment by victory-sokolov** [comment]
Hello, 
actually refresh token endpoint, doesn't return new `refresh_token`, it only returns `access_token`, sorry for misleading docstring.

Your refresh_token will be valid for the 30 days
