### ISSUE TITLE
Transactions date range filter not working

### ISSUE THREAD

**Issue by maxime-lambrechts** [nordigen/nordigen-python#5]
Hi, 
According to the example in the README it should be possible to fetch transactions for a specific date range. 
However, when I try this I get the following error: **get_transactions() got an unexpected keyword argument 'date_from'**.
Could it be that this functionality is not yet available in the last released version (v 1.0.1)?

![image](https://user-images.githubusercontent.com/58031212/166430126-d6755318-73e8-4d33-8684-a5d26c6b2bf9.png)

**Comment by victory-sokolov** [comment]
Hello.

We've just released a new version, could you please take a look and let us know if it works.

Thank You!

**Comment by maxime-lambrechts** [comment]
Thanks, it works perfectly now!
